state_cols = ['angle',
        'tgAngle',
        'segAngle',
        'curLapTime',
        'distFromStart',
        'lastLapTime',
        'speedX', 'speedY', 'speedZ',
        'track',
        'trackPos',
        'x',
        'y',
        'yaw']
